### ISSUE TITLE
Install on Barebone server

### ISSUE THREAD

**Issue by STRIXVERDEN** [lorien/sbin#2]
How to install sbin to the Barebone Ubuntu server?
My server uses LXC containers and i wanna test this product on Ubuntu LXC container without Heroku.
Can you explain any dependencies for compile or write a manual for bareboners.
This project is really interesting.

**Comment by lorien** [comment]
You need to have a python on your server. The app is developed for python3, maybe it could also run on python2. Assuming you have python3:

* clone the project to your server
* cd into root directory of the project
* run: make build
* run: ./migrate.py

To run the app in debug mode just run: python3 web.py
To run the app as daemon with your web-server: well, it is too general question and the answer would be quite long.

I do not use (zero experience) LXC containers, docker and all these things.

**Comment by STRIXVERDEN** [comment]
Thanks for your answer.
