### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by Fastidious** [lorien/sbin#4]
How do I get this to run, not on Heroku? Thanks!

**Comment by lorien** [comment]
This is WSGI application. Use any method you know to run python WSGI application.

**Comment by Fastidious** [comment]
Assuming `web.py` is the main CGI. Thanks, will try.

**Comment by lorien** [comment]
Here is the simple way to run the app (assuming you have pip installed).

* git clone https://github.com/lorien/sbin
* cd sbin
* sudo pip install -r requirements.txt
* sudo pip install gunicorn
* mkdir var
* python migrate # that will create sqlite tables
* gunicorn web:APP

Now you can use your application at http://localhost:8000
If you want to use it in production you can setup app instance daemon with supervisor and then proxy requests from real world via apache or nginx to the port where app instance is listening.
